from __future__ import annotations

import json
import re
import shlex
from pathlib import Path
from typing import Any

from .common import OwnDiffError
from .diff_collect import changed_source_files

PROMPT_VERSION = "owndiff.llm_questions.v1"

_SECRET_PATTERNS = [
    re.compile(r"AKIA[0-9A-Z]{16}"),
    re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"),
    re.compile(r"(?i)(api[_-]?key|secret|password|token)\s*[:=]\s*[\"']?[A-Za-z0-9_./+=-]{12,}"),
]
_BANNED_EXTERNAL_TERMS = (
    "web search",
    "internet",
    "google",
    "browse",
    "browser",
    "stackoverflow",
    "search online",
    "look up online",
    "latest version",
    "current version",
)
_GENERIC_OPTION_ARCHETYPES = {
    "ai_generated": re.compile(r"\b(ai|agent|model)\b.{0,40}\b(generated|produced|wrote|created)\b|\bgenerated by\b"),
    "tests_pass": re.compile(r"\btests?\s+(pass|passes|passed|passing)\b|\bpassing tests?\b"),
    "formatting_only": re.compile(r"\b(formatting|style|whitespace|variable names?|renam(?:e|ed|ing)|refactor(?:ed)? only)\b"),
    "skip_explanation": re.compile(r"\b(skip|omit|no need|does not need|unnecessary)\b.{0,50}\b(explain|explanation|mention|describe|review)\b"),
    "small_diff": re.compile(r"\b(diff|change|patch)\b.{0,30}\b(small|short|simple|tiny)\b"),
    "filename_only": re.compile(r"\b(filename|file name|path name|file path)\b.{0,50}\b(without|instead of|alone)\b|\bwithout tracing\b"),
    "approve_without_review": re.compile(r"\b(approve|accept|merge|push)\b.{0,60}\b(without|because it looks)\b"),
}
_QUESTION_SPECIFIC_STOPWORDS = {
    "about",
    "after",
    "answer",
    "because",
    "before",
    "behavior",
    "changed",
    "changes",
    "check",
    "code",
    "correct",
    "could",
    "diff",
    "does",
    "easy",
    "file",
    "from",
    "happen",
    "happens",
    "instead",
    "only",
    "owner",
    "path",
    "proves",
    "question",
    "risk",
    "should",
    "source",
    "test",
    "tests",
    "this",
    "understand",
    "what",
    "when",
    "where",
    "which",
    "with",
}


def build_agent_question_request(
    diff: dict[str, Any],
    risk: dict[str, Any],
    tests: dict[str, Any],
    question_plan: list[dict[str, Any]],
    question_config: dict[str, Any],
) -> dict[str, Any]:
    llm_config = question_config.get("llm", {})
    if not isinstance(llm_config, dict) or not llm_config.get("enabled", True):
        raise OwnDiffError("LLM question generation is required for ownership questions, but questions.llm.enabled is false.")
    prompt = build_llm_question_prompt(diff, risk, tests, question_plan, llm_config)
    return {
        "prompt_version": PROMPT_VERSION,
        "provider": "agent",
        "prompt": prompt,
        "response_shape": {
            "questions": [
                {
                    "dimension": "one of the dimensions in question_plan",
                    "difficulty": "easy",
                    "question": "specific question grounded in the diff facts",
                    "hint": "specific hint for this question that points to what to inspect without revealing the answer",
                    "options": [
                        {"id": "a", "text": "distinct answer choice"},
                        {"id": "b", "text": "distinct answer choice"},
                        {"id": "c", "text": "distinct answer choice"},
                        {"id": "d", "text": "distinct answer choice"},
                    ],
                    "correct_option_id": "one of a, b, c, d",
                    "expected_evidence": ["short evidence item"],
                    "rationale": "why this checks ownership",
                }
            ]
        },
    }


def build_llm_question_prompt(
    diff: dict[str, Any],
    risk: dict[str, Any],
    tests: dict[str, Any],
    question_plan: list[dict[str, Any]],
    llm_config: dict[str, Any] | None = None,
) -> str:
    llm_config = llm_config or {}
    count = len(question_plan)
    grounded_domains = _plan_risk_domains(question_plan)
    facts = {
        "risk_level": risk.get("risk_level", "unknown"),
        "risk_score": risk.get("risk_score", 0),
        "risk_domains": sorted(grounded_domains),
        "risk_reasons": [
            {"id": item.get("id"), "severity": item.get("severity"), "message": item.get("message")}
            for item in risk.get("reasons", [])
            if isinstance(item, dict)
            and (
                not str(item.get("id", "")).startswith("domain.")
                or str(item.get("id", ""))[len("domain.") :] in grounded_domains
            )
        ],
        "diff_summary": _source_diff_summary(diff),
        "changed_files": _changed_file_facts(diff),
        "test_gap": bool(tests.get("test_gap")),
        "changed_test_files": tests.get("changed_test_files", []),
        "missing_test_candidates": _missing_test_facts(tests),
        "question_plan": [
            {
                "id": item.get("id"),
                "dimension": item.get("dimension"),
                "context": item.get("context", {}),
            }
            for item in question_plan
        ],
        "sanitized_patch_excerpt": _sanitized_patch_excerpt(diff, _int_config(llm_config, "max_patch_chars", 12000)),
    }
    facts_json = json.dumps(facts, indent=2, sort_keys=True)
    dimensions = ", ".join(str(item.get("dimension")) for item in question_plan)

    return f"""You are OwnDiff's local question writer.

Goal:
Generate EASY multiple-choice ownership question specs for a developer reviewing an AI-assisted code diff.

Non-negotiable rules:
- Do not use web search, internet search, browsing, external documentation, package registries, issue trackers, or any fact outside the JSON facts below.
- Do not invent files, APIs, tickets, versions, vulnerabilities, benchmarks, tests, users, incidents, or business requirements.
- Ask questions answerable from the provided diff facts, sanitized patch excerpt, risk domains, and test-gap signal.
- Keep difficulty easy. These are ownership/comprehension checks, not trivia or trick questions.
- Focus on the code diff, behavior, runtime path, architecture assumption, test evidence, failure mode, blast radius, or rollback.
- If a fact is not present, ask what the developer should verify rather than pretending it is known.
- Do not include secrets. The patch excerpt may be redacted; never reconstruct redacted values.
- Return only valid JSON. No Markdown, no comments, no prose outside JSON.

Return exactly this JSON shape:
{{
  "questions": [
    {{
      "dimension": "one of: {dimensions}",
      "difficulty": "easy",
      "question": "specific question anchored to a changed file, risk domain, or test signal",
      "hint": "one specific hint for this question; point to the code behavior, risk, test, or failure signal to compare without revealing the answer",
      "options": [
        {{"id": "a", "text": "plausible answer choice"}},
        {{"id": "b", "text": "plausible answer choice"}},
        {{"id": "c", "text": "plausible answer choice"}},
        {{"id": "d", "text": "plausible answer choice"}}
      ],
      "correct_option_id": "one of a, b, c, d",
      "expected_evidence": ["short evidence item 1", "short evidence item 2"],
      "rationale": "why this question helps ownership"
    }}
  ]
}}

Output requirements:
- Generate exactly {count} question objects.
- Use only the dimensions listed in question_plan.
- Generate all four answer choices yourself; OwnDiff will not add template or fallback choices.
- Give every question exactly four choices with IDs a, b, c, and d and exactly one correct_option_id.
- Make incorrect choices plausible but clearly incomplete, unsafe, or contradicted by the supplied diff facts.
- Do not repeat an answer-choice sentence within or across questions.
- Do not use generic distractor ideas, even once. Avoid choices like "only say tests pass", "skip because AI generated it", "approve because the diff is small", or "only formatting changed".
- Make every answer choice question-specific: each choice should mention the changed file basename/path, a concrete symbol or behavior from the patch, the relevant risk domain, a test candidate, a failure symptom, or a rollback action.
- Generate a different `hint` for every question. Each hint must be one easy, question-specific sentence under 220 characters.
- Each hint must point to the exact behavior, code path, risk domain, test evidence, failure symptom, blast radius, or rollback detail to compare across the choices.
- Do not reuse hint wording across questions. Do not reveal the correct option letter or say which option is correct.
- Spread correct_option_id values across different letters when generating multiple questions.
- Every question or correct choice must mention a changed file path, changed file basename, or listed risk domain.
- Keep each question under 220 characters and each answer choice under 300 characters.
- Prefer practical wording a developer can answer after reading the diff.

JSON facts:
{facts_json}
"""


def validate_llm_questions(
    payload: Any,
    diff: dict[str, Any],
    risk: dict[str, Any],
    tests: dict[str, Any],
    question_plan: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    if not isinstance(payload, dict):
        raise ValueError("top-level response must be a JSON object")
    raw_questions = payload.get("questions")
    if not isinstance(raw_questions, list):
        raise ValueError("response must contain a questions list")
    if len(raw_questions) != len(question_plan):
        raise ValueError(f"expected {len(question_plan)} questions, got {len(raw_questions)}")

    allowed_dimensions = [str(item.get("dimension")) for item in question_plan]
    allowed_dimension_set = set(allowed_dimensions)
    anchors = _allowed_anchors(diff, risk, tests)
    path_like_allowed = _allowed_paths(diff, tests)
    context_by_dimension = {
        str(item.get("dimension")): item.get("context", {})
        for item in question_plan
        if isinstance(item.get("context", {}), dict)
    }

    result = []
    used_dimensions: set[str] = set()
    used_option_texts: set[str] = set()
    used_hints: set[str] = set()
    for index, raw_question in enumerate(raw_questions, start=1):
        if len(result) >= len(question_plan):
            break
        if not isinstance(raw_question, dict):
            raise ValueError(f"question {index} must be an object")

        dimension = str(raw_question.get("dimension", "")).strip()
        if dimension not in allowed_dimension_set:
            raise ValueError(f"question {index} uses unknown dimension {dimension!r}")
        if dimension in used_dimensions:
            raise ValueError(f"question {index} repeats dimension {dimension!r}")

        difficulty = str(raw_question.get("difficulty", "easy")).strip().lower()
        if difficulty != "easy":
            raise ValueError(f"question {index} must be easy, got {difficulty!r}")

        question = _clean_text(raw_question.get("question"), 220, f"question {index}")
        context = context_by_dimension.get(dimension, {})
        option_anchors = _option_specificity_terms(question, dimension, context, anchors)
        options = _clean_options(
            raw_question.get("options"),
            index,
            used_option_texts,
            option_anchors,
        )
        hint = _clean_hint(raw_question.get("hint"), index, question, dimension, context, option_anchors, used_hints)
        correct_option_id = str(raw_question.get("correct_option_id", "")).strip().lower()
        option_ids = {option["id"] for option in options}
        if correct_option_id not in option_ids:
            raise ValueError(f"question {index} correct_option_id must be one of a, b, c, or d")
        correct_answer = next(option["text"] for option in options if option["id"] == correct_option_id)
        expected_evidence = _clean_evidence(raw_question.get("expected_evidence"), index)
        rationale = _clean_optional_text(raw_question.get("rationale"), 220)

        option_text = " ".join(option["text"] for option in options)
        combined = f"{dimension} {question} {hint} {option_text} {' '.join(expected_evidence)}".lower()
        if any(term in combined for term in _BANNED_EXTERNAL_TERMS):
            raise ValueError(f"question {index} asks for external/web knowledge")
        grounded_text = f"{dimension} {question} {correct_answer}".lower()
        if not any(anchor in grounded_text for anchor in anchors):
            raise ValueError(f"question {index} is not anchored to changed files or risk domains")

        unknown_paths = sorted(_path_like_terms(combined) - path_like_allowed)
        if unknown_paths:
            raise ValueError(f"question {index} mentions unknown path(s): {', '.join(unknown_paths[:3])}")

        result.append(
            {
                "id": f"q{len(result) + 1}",
                "dimension": dimension,
                "question": question,
                "hint": hint,
                "required": True,
                "correct_answer": correct_answer,
                "options": options,
                "correct_option_id": correct_option_id,
                "expected_evidence": expected_evidence,
                "context": context,
                "rationale": rationale or "LLM-generated easy ownership question grounded in OwnDiff facts",
                "difficulty": "easy",
                "source": "llm",
            }
        )
        used_dimensions.add(dimension)

    if len(result) != len(question_plan):
        raise ValueError(f"expected {len(question_plan)} validated questions, got {len(result)}")
    correct_letters = {question["correct_option_id"] for question in result}
    min_distinct_letters = min(3, len(result))
    if len(result) > 1 and len(correct_letters) < min_distinct_letters:
        raise ValueError(
            "correct_option_id values are not spread across questions; regenerate with varied correct answer letters"
        )
    return result


def _plan_risk_domains(question_plan: list[dict[str, Any]]) -> set[str]:
    domains = {
        str(item.get("dimension", ""))[len("domain:") :]
        for item in question_plan
        if str(item.get("dimension", "")).startswith("domain:")
    }
    for item in question_plan:
        context = item.get("context", {})
        if not isinstance(context, dict):
            continue
        for domain in str(context.get("risk_domains", "")).split(","):
            domain = domain.strip()
            if domain:
                domains.add(domain)
    return domains


def _int_config(config: dict[str, Any], key: str, default: int) -> int:
    try:
        value = int(config.get(key, default))
    except (TypeError, ValueError):
        return default
    return value if value > 0 else default


def _changed_file_facts(diff: dict[str, Any]) -> list[dict[str, Any]]:
    facts = []
    for item in changed_source_files(diff)[:20]:
        facts.append(
            {
                "path": item.get("path"),
                "status": item.get("status"),
                "additions": item.get("additions"),
                "deletions": item.get("deletions"),
                "language": item.get("language"),
                "is_test": bool(item.get("is_test")),
            }
        )
    return facts


def _missing_test_facts(tests: dict[str, Any]) -> list[dict[str, Any]]:
    result = []
    for item in tests.get("missing_test_candidates", [])[:10]:
        if not isinstance(item, dict):
            continue
        result.append({"path": item.get("path"), "expected": item.get("expected", [])[:3]})
    return result


def _sanitized_patch_excerpt(diff: dict[str, Any], max_chars: int) -> str:
    patch_path = diff.get("patch_path")
    if not patch_path:
        return ""
    path = Path(str(patch_path))
    if not path.exists():
        return ""
    text = path.read_text(encoding="utf-8", errors="replace")
    source_paths = {
        str(item.get("path", "")).replace("\\", "/")
        for item in changed_source_files(diff)
        if str(item.get("path", "")).strip()
    }
    text = _filter_patch_to_paths(text, source_paths)
    sanitized = []
    for line in text.splitlines():
        if any(pattern.search(line) for pattern in _SECRET_PATTERNS):
            prefix = line[:1] if line[:1] in {"+", "-", " "} else ""
            sanitized.append(f"{prefix}[owndiff:redacted-secret-like-line]")
        else:
            sanitized.append(line)
    excerpt = "\n".join(sanitized)
    if len(excerpt) > max_chars:
        return excerpt[:max_chars] + "\n[owndiff:patch excerpt truncated]"
    return excerpt


def _source_diff_summary(diff: dict[str, Any]) -> dict[str, int]:
    source_files = changed_source_files(diff)
    additions = sum(int(item.get("additions", 0)) for item in source_files)
    deletions = sum(int(item.get("deletions", 0)) for item in source_files)
    return {
        "files_changed": len(source_files),
        "insertions": additions,
        "deletions": deletions,
        "lines_changed": additions + deletions,
    }


def _filter_patch_to_paths(text: str, allowed_paths: set[str]) -> str:
    if not allowed_paths:
        return ""
    kept_blocks = []
    for block in re.split(r"(?=^diff --git )", text, flags=re.MULTILINE):
        if not block.startswith("diff --git "):
            continue
        header = block.splitlines()[0]
        try:
            parts = shlex.split(header)
        except ValueError:
            continue
        paths = {
            value[2:] if value.startswith(("a/", "b/")) else value
            for value in parts[2:4]
        }
        if paths & allowed_paths:
            kept_blocks.append(block.rstrip())
    return "\n\n".join(kept_blocks)


def _clean_text(raw: Any, max_length: int, label: str) -> str:
    if not isinstance(raw, str):
        raise ValueError(f"{label} must be a string")
    text = " ".join(raw.strip().split())
    if not text:
        raise ValueError(f"{label} must not be empty")
    if len(text) > max_length:
        raise ValueError(f"{label} is too long")
    return text


def _clean_optional_text(raw: Any, max_length: int) -> str:
    if not isinstance(raw, str):
        return ""
    return " ".join(raw.strip().split())[:max_length]


def _clean_options(
    raw: Any,
    index: int,
    used_option_texts: set[str],
    option_anchors: set[str],
) -> list[dict[str, str]]:
    if not isinstance(raw, list) or len(raw) != 4:
        raise ValueError(f"question {index} options must contain exactly four choices")

    options: list[dict[str, str]] = []
    seen_ids: set[str] = set()
    local_texts: set[str] = set()
    for option_number, item in enumerate(raw, start=1):
        if not isinstance(item, dict):
            raise ValueError(f"question {index} option {option_number} must be an object")
        option_id = str(item.get("id", "")).strip().lower()
        if option_id not in {"a", "b", "c", "d"} or option_id in seen_ids:
            raise ValueError(f"question {index} options must use unique IDs a, b, c, and d")
        text = _clean_text(item.get("text"), 300, f"question {index} option {option_id}")
        normalized = text.casefold()
        if normalized in local_texts:
            raise ValueError(f"question {index} repeats an answer choice")
        if normalized in used_option_texts:
            raise ValueError(f"question {index} repeats an answer choice used by another question")
        if not _is_question_specific_option(text, option_anchors):
            raise ValueError(f"question {index} option {option_id} is generic; make every answer choice specific to this diff")
        for archetype in _generic_option_archetypes(text):
            raise ValueError(
                f"question {index} option {option_id} uses generic distractor idea {archetype!r}; "
                "make answer choices specific to the changed behavior, risk, test, failure, or rollback"
            )
        options.append({"id": option_id, "text": text})
        seen_ids.add(option_id)
        local_texts.add(normalized)

    if seen_ids != {"a", "b", "c", "d"}:
        raise ValueError(f"question {index} options must use IDs a, b, c, and d")
    used_option_texts.update(local_texts)
    return options


def _clean_hint(
    raw: Any,
    index: int,
    question: str,
    dimension: str,
    context: dict[str, Any],
    option_anchors: set[str],
    used_hints: set[str],
) -> str:
    hint = _clean_text(raw, 220, f"question {index} hint")
    normalized = hint.casefold()
    if normalized in used_hints:
        raise ValueError(f"question {index} repeats a hint used by another question")
    if _reveals_answer_letter(hint):
        raise ValueError(f"question {index} hint reveals the answer choice")
    if not _is_question_specific_option(hint, option_anchors):
        raise ValueError(f"question {index} hint is generic; make it specific to this question and diff")
    for archetype in _generic_option_archetypes(hint):
        raise ValueError(
            f"question {index} hint uses generic distractor idea {archetype!r}; "
            "make hints point to the changed behavior, risk, test, failure, blast radius, or rollback detail"
        )
    question_terms = _specific_tokens(question)
    context_terms = {
        token
        for value in context.values()
        if isinstance(value, str)
        for token in {*_specific_tokens(value), *_path_tokens(value)}
    }
    dimension_terms = _specific_tokens(dimension.replace("_", " ").replace(":", " "))
    hint_terms = _specific_tokens(hint) | _path_tokens(hint)
    if not hint_terms & (question_terms | context_terms | dimension_terms | option_anchors):
        raise ValueError(f"question {index} hint is not pertinent to the question or answer choices")
    used_hints.add(normalized)
    return hint


def _reveals_answer_letter(text: str) -> bool:
    lowered = text.casefold()
    return bool(
        re.search(r"\b(answer|choice|option)\s+(is|should be|=)\s*[a-d]\b", lowered)
        or re.search(r"\bchoose\s+(option\s+)?[a-d]\b", lowered)
        or re.search(r"\b[a-d]\s+is\s+(correct|right)\b", lowered)
    )


def _generic_option_archetypes(text: str) -> set[str]:
    lowered = text.casefold()
    return {
        name
        for name, pattern in _GENERIC_OPTION_ARCHETYPES.items()
        if pattern.search(lowered)
    }


def _is_question_specific_option(text: str, option_anchors: set[str]) -> bool:
    lowered = text.casefold()
    return any(len(anchor) >= 3 and anchor in lowered for anchor in option_anchors)


def _option_specificity_terms(
    question: str,
    dimension: str,
    context: dict[str, Any],
    anchors: set[str],
) -> set[str]:
    terms = {anchor.casefold() for anchor in anchors if len(anchor) >= 3}
    for value in context.values():
        if isinstance(value, str):
            terms.update(_specific_tokens(value))
            terms.update(_path_tokens(value))
    terms.update(_specific_tokens(question))
    if dimension.startswith("domain:"):
        terms.update(_specific_tokens(dimension.removeprefix("domain:").replace("_", " ")))
    return {term for term in terms if len(term) >= 3}


def _specific_tokens(text: str) -> set[str]:
    tokens = {
        token.casefold()
        for token in re.findall(r"[A-Za-z][A-Za-z0-9_-]{2,}", text)
        if token.casefold() not in _QUESTION_SPECIFIC_STOPWORDS
    }
    return tokens


def _path_tokens(text: str) -> set[str]:
    tokens: set[str] = set()
    for term in _path_like_terms(text.casefold()):
        tokens.add(term)
        tokens.add(Path(term).name.casefold())
        tokens.add(Path(term).stem.casefold())
    return {token for token in tokens if token and token not in _QUESTION_SPECIFIC_STOPWORDS}


def _clean_evidence(raw: Any, index: int) -> list[str]:
    if not isinstance(raw, list):
        raise ValueError(f"question {index} expected_evidence must be a list")
    evidence = []
    for item in raw[:4]:
        if isinstance(item, str) and item.strip():
            evidence.append(" ".join(item.strip().split())[:120])
    if not evidence:
        raise ValueError(f"question {index} expected_evidence must not be empty")
    return evidence


def _allowed_anchors(diff: dict[str, Any], risk: dict[str, Any], tests: dict[str, Any]) -> set[str]:
    anchors: set[str] = set()
    for path in _allowed_paths(diff, tests):
        anchors.add(path.lower())
        anchors.add(Path(path).name.lower())
    for domain in risk.get("domains", []):
        domain_text = str(domain).lower()
        anchors.add(domain_text)
        if domain_text == "auth":
            anchors.add("authentication")
            anchors.add("session")
        if domain_text == "authorization":
            anchors.add("permission")
            anchors.add("tenant")
        if domain_text == "dependencies":
            anchors.add("dependency")
            anchors.add("package")
    return {anchor for anchor in anchors if anchor}


def _allowed_paths(diff: dict[str, Any], tests: dict[str, Any]) -> set[str]:
    paths = {
        str(item.get("path", "")).lower()
        for item in changed_source_files(diff)
        if str(item.get("path", "")).strip()
    }
    paths.update(_path_aliases(paths))
    paths.update(str(path).lower() for path in tests.get("changed_test_files", []) if str(path).strip())
    paths.update(_path_aliases(paths))
    for item in tests.get("missing_test_candidates", []):
        if not isinstance(item, dict):
            continue
        if item.get("path"):
            paths.add(str(item["path"]).lower())
            paths.update(_path_aliases({str(item["path"]).lower()}))
        for expected in item.get("expected", [])[:5]:
            if str(expected).strip():
                paths.add(str(expected).lower())
                paths.update(_path_aliases({str(expected).lower()}))
    return paths


def _path_aliases(paths: set[str]) -> set[str]:
    aliases: set[str] = set()
    for path in paths:
        parts = [part for part in path.replace("\\", "/").split("/") if part]
        if not parts:
            continue
        aliases.add(Path(path).name.lower())
        for index in range(1, len(parts)):
            aliases.add("/".join(parts[index:]).lower())
    return aliases


def _path_like_terms(text: str) -> set[str]:
    terms = set()
    extension_pattern = r"(?:py|js|jsx|ts|tsx|mjs|cjs|mts|cts|go|java|rb|rs|php|cs|kt|swift|sql|ya?ml|json|toml|tf|sh)"
    pattern = rf"\b[\w.-]+(?:/[\w.-]+)+\.{extension_pattern}\b|\b[\w.-]+\.{extension_pattern}\b"
    for match in re.finditer(pattern, text):
        terms.add(match.group(0).lower())
    return terms
